### ISSUE TITLE
Hover background on text makes it unreadable

### ISSUE THREAD

**Issue by PlusMD** [JohnWolfson/LPG-Launcher#91]
1)Launch LPG Launcher
2) Hover over Library or About

![image](https://user-images.githubusercontent.com/25768843/200193686-e89a9661-4a79-47fe-bd6c-6b221196d08d.png)

**Comment by IstalriSkolir** [comment]
Suggested colour for hover is a darker shade than the normal background for better contrast with the text colour, should be the next ticket to tackle for better user experience
